- module: kubernetes
  metricsets:
    - node
    - system
    - pod
    - container
    - volume
  period: 10s
  host: ${NODE_NAME}
  hosts: [ "https://${NODE_NAME}:10250" ]
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  ssl.verification_mode: "none"
    # If there is a CA bundle that contains the issuer of the certificate used in the Kubelet API,
    # remove ssl.verification_mode entry and use the CA, for instance:
    #ssl.certificate_authorities:
  #- /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
# Currently `proxy` metricset is not supported on Openshift, comment out section
- module: kubernetes
  metricsets:
    - proxy
  period: 10s
  host: ${NODE_NAME}
  hosts: [ "localhost:10249" ]